version: '3'

services:
  db:
    image: postgres
    environment:
      POSTGRES_DB: Products
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1711
    ports:
      - 5432:5432

  frontend:
    build: ./frontend
    ports:
      - 3000:3000

  backend:
    build: ./backend
    ports:
      - 5000:5000
    depends_on:
      - db

     